- name: Pull portfolio image
  docker_container:
    name: portfolio
    image: saiusesdocker/portfolio:latest
    state: started
    restart_policy: unless-stopped
    pull: yes
    recreate: yes
    ports:
      - "80:80"