- name: Remove old container
  docker_container:
    name: portfolio
    state: absent

- name: Run portfolio container
  docker_container:
    name: portfolio
    image: saiusesdocker/portfolio:latest
    state: started
    pull: yes
    restart_policy: unless-stopped
    ports:
      - "80:80"